### ISSUE TITLE
The plugin spams console in debug builds with "NPC Spawned" statements.

### ISSUE THREAD

**Issue by umer-rs** [pajlads/StealingArtefacts#12]
https://github.com/pajlads/StealingArtefacts/blob/661fc3edf4798812e0321fc027af95dbbc23d82c/src/main/java/io/cbitler/stealingartefacts/StealingArtefactsPlugin.java#L221

**Comment by pajlada** [comment]
Thanks for the report - I'm in the progress of making a release PR to the plugin hub that'll include this fix
